system_prompt: null
first_prompt: null
user_prompt: null
assistant_response: null
abbreviations: null
model: null
temperature: 0.8
max_tokens: 100000
use_summary: true
history_path: "story.md"
separator: "----"
interrupt_flag: false
part_number: 0
write_interval: 1.0
debug: false
print_messages: true
print_output: false
include_reasoning: true
write_reasoning: true
reasoning_header: "### Reasoning"
print_reasoning: false